[gcp_service_account]
type = "service_account"
project_id = "alistounimar"
private_key_id = "62c33d3eba9e0871c3bd0b2b490fc9b3233c1db6"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDVqr1VXk5pLDG0
HuCvvNSrmjVuCPPClmlHyPxkDNofiC8pOr+tas47aFlERGgQI8sNoeIS+f4x6Wdh
Q2iHdLSGUaiCIwvD8/PffJJUjXx7UXBZ4Eh0MooHJPdhKDsvEVxRvWWRU2UJG9bM
TI3tOuncBBbBhvpL7yP4F5Om+UCjTM9pzTb1RTMij8ffY6XDWgtnctDJ5Uu3MZ2g
OekIFEQrNtEPuTadlNQgtUNQYPzIkk7nsXF+zebv/8gYEPsDrG7gQPG03e0Jx/sv
opidrxegB078SMAJSEdM8cPwvIEFQbUsanNSixbTeZQg+x8HGyvGDi9OORXaJVij
vK00Q+cHAgMBAAECggEAFgwktkrhZ2vWgyIOiEPBZCWo7r5AvOr9WRltpbtHxKou
R6BWyAO13R5y2579Z/DxkmoKZG/kYW0WrEwi3JtXx2Zkr20DWUhyeTSm+s+QsT7h
i3yfrVHLuVoApsdaeAxgDNUwxlKnIc38F5+so3aJTBkl6flOGYjHGuH/6+JbX54s
k74X1DZ/Z2uoB8S4yAnvZY4aKwZaxB59e61GNaCh0qAI2M9+sYmarz6p8xIQq10+
u5/CU7d2xYt8iH27C7WFBbwc+XckfZ4XONP3/LEM1e12FHscer+KL4+bSm1FzTIK
mNo/uEH2EATMwr8gihsbPUB/DMZE0Opk/+9Y2hBLrQKBgQD1pKk+f/rQ8ZxUMXWP
m9PybbeOCmi9NRNifvVX/obQ6xtu8RsJ3064WwJkAhHaWSH3mQErRMb3f5Jbsb+S
G8CkFzp+MYCpHJeW/tDko8grckto5tWp92iF1SepvVUMKHTLH9XSdXQrs+9J9Oi3
6Yq3u1nG11vUmz33b+/GiknXswKBgQDerPG216pc0Zva+Myev0xtOVkmH8p4zIhu
fnWJkIO5H135BM5iTtpX7k4JNBMRMdTrl/V1KzbmKgZWzcSaiYZspamonzPtrl08
17ffmVSXAP7/d+Lp72ytMTvr5uBNdK8XeurN7kTrilYwhehynWXaOFS8Jz3Nfptx
sexA9BfJXQKBgASHHHeCdGUVjwQeRUR4Yte9Hf0IRBX4vHq8TFlq36FKNB8/Yng0
HYdYZhrhzuJvcijWMSdTBTfaqh/2jslqqYpcwz9AOlbjqAeoesE8I5xpZupwFtAj
N1IAM9L1InQu6rgzxgUzFQkZL/f1A7UgIOZyFZ2Mqqyoj+PXtFu8gM/xAoGBAJJv
NP3C0dv8U/wqRZXXw5DId+HkYigSiV3wd6chjB4/jHLoQDjSFjBhHJxczHUwSg8s
fVSyOIYf+M84viPKcMYeI3YqS+HwGoyaZ+b5VHGBTDAATQ7+Tn+OsxMtXzBQnZxZ
TvRhzpz++jMqvHQzIfnhtYeOXsw2iE66bN1CKCpZAoGAPrBLU89nizp28pZVjJ+q
pGNmInsD60soH2a3MYu7RkkIp/hAHvFdTf/RJKpN9Eeauwhtr1gNCrz+i5OAJ6Kl
mhe/Y0dIASBeQHjSWy9YCG3nmqr34nxpGCToxIc5rgKHzIflBIcot6kKuaJZ4OM9
BP1tTG0xUF/WTZbkLQqogfE=
-----END PRIVATE KEY-----"""
client_email = "streamlit-registrador@alistounimar.iam.gserviceaccount.com"
client_id = "109827752142638688604"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-registrador@alistounimar.iam.gserviceaccount.com"
universe_domain = "googleapis.com"